### PR TITLE
Inverted comma

### PR DESCRIPTION
**Pull request by marcobischoff**
#222 As there are some countries which uses the inverted comma as thousand separator I've added this to the currency.

### CODE REVIEW

**Comment by hql287** [comment]
Hah, this is interesting. How do you type the inverted comma on a US keyboard?

**Comment by marcobischoff** [comment]
You‘re right, the inverted comma is not the right char; instead it is an apostrophe which is used and this should also be available on an US keyboard. I will make ab update on this.

**Comment by hql287** [comment]
Yup, it seems that you're using right single quote `&rsquo;`

**Comment by hql287** [comment]
Let's resolve #129 first then we can merge this. 
Please take a look at #224 and let me know if you want to change or add anything to it. 
Thanks.

**Comment by hql287** [comment]
@marcobischoff: Why do you try to solve #220 with this PR? I'm confused. Also, please use `styled-component` instead of plain CSS.

I think it would be best if you create a clean (new) PR with only the changes necessary to fix #222. 
Btw, what countries use inverted comma/ apostrophe as the thousand separator, I'm curious?

**Comment by marcobischoff** [comment]
@hql287 My repo is/was a little bit messed up. I will create a new PR with styled-component.
Switzerland is a country which use this.

**Comment by hql287** [comment]
@marcobischoff Thanks! 👍

**Pull request closed without merging**
