### PR TITLE
Add new languages

### PR DESCRIPTION
**Pull request by hql287**
Replace #207. Languages to be added & its respective translation progress:

In progress:

- [ ] [Italian (92%)](https://crowdin.com/project/manta/it)
- [ ] [Japanese (92%)](https://crowdin.com/project/manta/ja)
- [ ] [Korean (92%)](https://crowdin.com/project/manta/ko)
- [ ] [Portuguese (92%)](https://crowdin.com/project/manta/pt-PT)
- [ ] [Portuguese, Brazilian (89%)](https://crowdin.com/project/manta/pt-BR)
- [ ] [Turkish (89%)](https://crowdin.com/project/manta/tr)

Finished:

- [x] [Slovak (100%)](https://crowdin.com/project/manta/sk)
- [x] [Spanish (100%)](https://crowdin.com/project/manta/es-ES)
- [x] [Tagalog (100%)](https://crowdin.com/project/manta/tl)

Approved:

- [x] [French (100%)](https://crowdin.com/project/manta/fr)
- [x] [Chinese Simplify (100%)](https://crowdin.com/project/manta/zh-CN)
- [x] [German (100%)](https://crowdin.com/project/manta/de)
- [x] [Indonesian (100%)](https://crowdin.com/project/manta/id)
- [x] [Vietnamese (100%)](https://crowdin.com/project/manta/vi)

It would be nice to support at least 10 languages with this release 😜

### CODE REVIEW

**Comment by hql287** [comment]
@jens-t I merged #224 and forgot that it introduced some new keywords so now I need the translation for those new keywords in order to add that language to Manta. As a result, #207 become obsolete and this is the new PR to replace it.   

What's your native language? Can you help me to add those missing translation on Crowdin? I can set you up as a proofreader for that language if you're up to it. Thanks!

**Comment by jens-t** [comment]
Ah, ok. I can finish the german one. Maybe it is a good idea to merge before all languages are completed and use "en-US" as fallback for missing terms. It's just temporary and with new features there will be new terms and the translations will get uncomplete again. So a general fallback solution for missing terms could help. what do you think?

**Comment by jens-t** [comment]
Ok, german translation on crowdin is complete. What is the meaning of  the "Net ..." labels?

**Comment by hql287** [comment]
> Ah, ok. I can finish the german one. Maybe it is a good idea to merge before all languages are completed and use "en-US" as fallback for missing terms. 

Yes, this is how it works at the moment. But I would like to make sure this release has all the necessary translation as it's the first one that supports multiple languages. 

> It's just temporary and with new features there will be new terms and the translations will get uncomplete again. 

It's true, and I think having the translation for all the new keywords should be part of the PR. I'm writing about this in the contributing guideline in #226 where it goes into more details on this.

**Comment by hql287** [comment]
> Ok, german translation on crowdin is complete. 

Awesome! Thanks 👍

> What is the meaning of the "Net ..." labels?

I think it's just a shorter way of saying "you have exactly 7, 10, 30 ... days to make the payment". I think you can just keep it as `Net X` as it always goes with the description.

**Comment by jens-t** [comment]
> It's true, and I think having the translation for all the new keywords should be part of the PR. I'm writing about this in the contributing guideline in #226 where it goes into more details on this.
Ok, hope that goes well and no pull requests are blocked too long by missing new translation terms :) Waiting for the contribution guidelines then. Thanks for the info!

**Comment by hql287** [comment]
Five languages have been approved. Not too shabby, guys!!!👍

**Comment by qpixHassaballah** [comment]
Hey I am working on an arabic translation on crowdin will it be in the next version? 
I already see that someone already attempted multiple translations a year ago

**Pull request merged**
