### PR TITLE
fixed the multiple scrollbars bug for linux/windows

### PR DESCRIPTION
**Pull request by jens-t**
fix for #182

### CODE REVIEW

**Comment by jens-t** [comment]
now all scrollbars should be gone till they are needed again :laughing:

**Comment by hql287** [comment]
@jens-t:  Can I have some screenshots, please? :)

**Comment by jens-t** [comment]
here you go ...

bildschirmfoto-20180302132547-3247x1999
bildschirmfoto-20180302132618-1379x1940
bildschirmfoto-20180302132640-1583x1314
bildschirmfoto-20180302132713-1004x540

**Comment by hql287** [comment]
Looks good to me. Will check on `macOS` now.

**Comment by hql287** [comment]
@jens-t Can you confirm if this fixes https://github.com/hql287/Manta/issues/202 as well? Thanks!

**Comment by hql287** [comment]
Can you try `Ctrl+T`?

**Comment by jens-t** [comment]
Yeah, `Ctrl + T` works ... do you also have some infos about the persistence of the data?

**Comment by jens-t** [comment]
#202 is no `overflow. scroll` problem. so not really related, but i commit a fix for this into this branch ...

**Comment by jens-t** [comment]
the height of the content is too big:
bildschirmfoto-20180302145132-1477x1273

**Comment by jens-t** [comment]
> Or are the indexeddb's of the app shared between the instances?

Yes, that's it. Deleted the indexed db's and the data is gone after restart.

**Comment by hql287** [comment]
> How can i delete all my app data? 

screen shot 2018-03-02 at 20 52 52

**Comment by hql287** [comment]
> Can you please give me some infos about where and how the data is stored? 

I don't think I'm qualified enough to explain this question. It's still quite a big mystery to me. 😂 

Would love to know if you found something.

**Comment by jens-t** [comment]
Should this PR be part of 1.1.3? I'm working on the #202 bug now ...

**Comment by hql287** [comment]
I'm already testing v1.1.3. This and your other PRs will be included in the next one – next Friday. 

Take your time :)

**Comment by jens-t** [comment]
Time taken, 4ed0472 is the fix for #202 :)
The slideImages caused  an overflow in the slideWrapper ... disabled overflow for the slideWrapper.

**Comment by hql287** [comment]
Can you do a screenshot? I think I can include this one with v1.1.3. Thanks!

**Comment by hql287** [comment]
@jens-t: C'mon man, I need to see that screenshot 😂

**Comment by jens-t** [comment]
Sorry, 1 minute ... :laughing:

**Comment by jens-t** [comment]
And it's german :tada: nice work with the multilanguage support!

**Comment by hql287** [comment]
It's kinda strange, but this thing somehow looks better with German written on it 😅

**Pull request merged**
