### PR TITLE
[WIP] Allow users to create Estimates

### PR DESCRIPTION
**Pull request by farfromrefug**
I needed to create estimates.
So i simply added a new status and make the templates print "estimate" instead of "invoice" with this status.

I you are ok with the way i have done it i will add the missing locales.

### CODE REVIEW

**Comment by hql287** [comment]
@farfromrefug: Thanks for the PR 👍. 

I like the idea but I think the implementation is a bit hacky at the moment because statuses are not being used correctly. I think a better approach would be: 

* Add a new field (could be a checkbox or toggle) in the form to let the user choose what to create (an invoice or an estimate). 
* This value would get saved with other data of the record to the "DB". It also can be edited later. Eg converting an estimate to an invoice
* We can use this value to display "Invoice" or "Estimate" in the template. 

In the future, if you need to create a new type of document, eg a receipt, just repeat the above steps. This approach is future-proof. 

Btw, for a non-trivial feature like this, maybe next time you should create an issue first. That way we can discuss the implementation detail in advance and possibly will save you a bit of time. 

Let me know what you think. In the meantime, I'll see if I can add this feature to [the new design](https://github.com/hql287/Manta/issues/283)

**Comment by farfromrefug** [comment]
@hql287 ok will look at it. And i did not create an issue just because i did not have time. I needed an estimate so i implemented it ;)

**Comment by hql287** [comment]
Ah, ok. Hope it worked out well for you. 👍 
Let me know if you still want to finish the PR with this approach. 
Thanks!

**Comment by robgha01** [comment]
This kind of feature is someting i also needed and i were thinking if we could have a seperate section below Invoice called estimates where we can create em like we do with invoice then if it gets a "go" we could convert it to an invoice ? i think its like @hql287 pointed out above.

How i solved it for now is save the pdf file and import it to office word and modify it there however would be awsome to have it all in Manta.

**Comment by mikkelking** [comment]
@robgha01  This is a really useful feature.. Are you able to do as @hql287 suggests? 

Many of my customers want a quote first, and then they raise a purchase order, at which time I convert it to an invoice for payment. I also need a place to put the Purchase Order Number on the page.

**Comment by farfromrefug** [comment]
@mikkelking sorry no did not have the time. As this repo is not really maintained anymore, i decided to keep my approach. I now maintain my own version in my fork.

**Comment by hql287** [comment]
> As this repo is not really maintained anymore
@farfromrefug: I'm getting back to this now. Still, it's not easy to find time to work on open source and keeping a full-time job. But I would still be happy to review your work if that's possible.

**Pull request closed without merging**
