### PR TITLE
Translation of settings page

### PR DESCRIPTION
**Pull request by DarkSmile92**
- added json file for translation of settings page
- included german and english (to be validated via crowdin)
- created file for vietnamese and french with english content (to be translated via crowdin)

### CODE REVIEW

**Comment by DarkSmile92** [comment]
@hql287 can you please review the changes?

**Comment by hql287** [comment]
@DarkSmile92 Yes, I'm doing it right now. Thanks! :)

**Comment by DarkSmile92** [comment]
@hql287 I did not see any comments in the code, so just to make sure I got it right:
I revert the number changes in this PR, create a new one on base of the `dev` branch and rename `general.language` to `general.locale`?

**Comment by hql287** [comment]
@DarkSmile92: Sorry for taking a bit long to get back to this, I had a meeting yesterday. 
Anyway, I think I should have told you that I'm already working on translating the rest of the components in the `mainWindow`. 

So here's what we can do right now:

- We'll still keep this PR,
- I'll finish the `mainWindow`'s components,
- You can translate `previewWindow`, `tourWindow`, `dialog` and commit directly to this PR if you like. But let me know which one you will be working on so we don't step on each other's toes. 

Regarding [this commit](https://github.com/hql287/Manta/pull/191/commits/4ef32843f09af4404b8e5fc0c0dc3d87120b44d9), since it's not related to the translation, can you make a new PR for it? And just use `general.language` for now. Let me know what you think.  

Thanks!

**Comment by DarkSmile92** [comment]
@hql287 okay that makes it clear, I wanted to know if I should open a new PR for the last commit 👍 
I leave the decision to you, if you want me to translate one of the other windows, I'll be happy to do so. But if you want me to I can also take on other issues here.
Thanks :)

And sorry for some confusion...

**Comment by hql287** [comment]
@DarkSmile92 Alright, since you're already working on other issues, I think it might be easier for me to do the rest of the translation. So I think you can change this issue to what you like to fix with the last commit. Sounds good?

**Comment by DarkSmile92** [comment]
@hql287 I just opened a separate [>PR<](https://github.com/hql287/Manta/pull/192) for the fix with the last commit to make things clear.
Should we delete this one?

**Comment by hql287** [comment]
> @hql287 I just opened a separate >PR< for the fix with the last commit to make things clear.
> Should we delete this one?

Ok, closed!

**Pull request closed without merging**
