### PR TITLE
German string translation and selection

### PR DESCRIPTION
**Pull request by marcobischoff**
#207 This is the german language and selection of if in the "General" tab in the "Settings" view.

### CODE REVIEW

**Comment by hql287** [comment]
Shouldn't this be part of https://github.com/hql287/Manta/pull/207?

**Comment by marcobischoff** [comment]
Would make sense, how can I add this to #207 new PR?

**Comment by hql287** [comment]
You can create a new PR to the [branch](https://github.com/hql287/Manta/tree/add-more-languages) of the #217 PR

**Comment by hql287** [comment]
But I would suggest waiting until I resolve the current conflict on that branch first. Will do it after either #216 or #224 is merged.

**Pull request closed without merging**
