### PR TITLE
Some css Fix

### PR DESCRIPTION
**Pull request by c0b41**
Before:
ekran goruntusu - 2018-01-12 22 03 18
ekran goruntusu - 2018-01-12 22 03 47

After:

ekran goruntusu - 2018-01-12 22 05 54
ekran goruntusu - 2018-01-12 22 06 12

### CODE REVIEW

**Comment by hql287** [comment]
Ahh, Linux users will thank you for this @c0b41 :)

**Comment by c0b41** [comment]
Also same fix affect Windows

image

**Comment by hql287** [comment]
on macOS, I have this black scrollbar:

screen shot 2018-01-15 at 16 34 25

**Comment by hql287** [comment]
This is also ... weird

**Comment by c0b41** [comment]
@hql287 Actually i change scrollbar, is it OK for you? maybe i can remove

**Comment by hql287** [comment]
@c0b41 Sorry for taking a bit long to get back to you. Is it possible to do not alter the default behaviour of Chrome on Mac? The hover issue is gone but I still get the black scroll bar: 

screen shot 2018-01-19 at 19 03 24

**Comment by c0b41** [comment]
@hql287 updated.

**Comment by hql287** [comment]
@c0b41 Why closed?

**Pull request closed without merging**
