### PR TITLE
Various fixes

### LINKED ISSUE #49: accent color inconsistently applied
when using the default non-custom accent color, the "INVOICE" font color is black and the dividers are lime-green

but using custom accent color, both the "INVOICE" font color and divider changed to the same custom accent color

### PR DESCRIPTION
**Pull request by hql287**
Fixed #49, #116 and #118

### CODE REVIEW

**Comment by hql287** [comment]
@mathieudutour Does this look right to you?

**Comment by mathieudutour** [comment]
looks good, the diff is a bit too noisy for me to review but it should be fine :)

(btw, what do you think about using eslint/prettier? it would make the diffs more readable and consistent. Happy to throw a quite PR if you want)

**Comment by hql287** [comment]
I'm using both `eslint` and `prettier` atm, or did you mean using `prettier` as a git hook?

**Comment by mathieudutour** [comment]
yeah, it's not enforced anywhere and it's not in the deps so my (and the default) editor config doesn't pick it up

**Comment by hql287** [comment]
A PR sounds good to me. This might be helpful for other contributors, too. Thanks!

**Pull request merged**
