### PR TITLE
Support multiple languages

### LINKED ISSUE #9: Support Multiple Languages
**UPDATE:**

Thank you very much for your patience, now you can help translate Manta on [Crowdin](https://crowdin.com). 

[Please follow this instruction to start translating the app](https://github.com/hql287/Manta/wiki/Translating-Manta).

Thanks!

**Original Post:**

I think this would be a very nice feature to have. 
But first, let me know which languages you would like Manta to support.

[](https://api.gh-polls.com/poll/01C10PCX59FS1ZNX9T813Q2PSM/France/vote)
[](https://api.gh-polls.com/poll/01C10PCX59FS1ZNX9T813Q2PSM/Spanish/vote)
[](https://api.gh-polls.com/poll/01C10PCX59FS1ZNX9T813Q2PSM/Portuguese/vote)
[](https://api.gh-polls.com/poll/01C10PCX59FS1ZNX9T813Q2PSM/Chinese/vote)
[](https://api.gh-polls.com/poll/01C10PCX59FS1ZNX9T813Q2PSM/Japanese/vote)
[](https://api.gh-polls.com/poll/01C10PCX59FS1ZNX9T813Q2PSM/Korean/vote)
[](https://api.gh-polls.com/poll/01C10PCX59FS1ZNX9T813Q2PSM/Italian/vote)
[](https://api.gh-polls.com/poll/01C10PCX59FS1ZNX9T813Q2PSM/Russian/vote)
[](https://api.gh-polls.com/poll/01C10PCX59FS1ZNX9T813Q2PSM/Vietnamese/vote)
[](https://api.gh-polls.com/poll/01C10PCX59FS1ZNX9T813Q2PSM/Thai/vote)
[](https://api.gh-polls.com/poll/01C32ZRKE5KJ746Y6HN65VGRN5/German/vote)
[](https://api.gh-polls.com/poll/01C32ZRKE5KJ746Y6HN65VGRN5/Dutch/vote)
[](https://api.gh-polls.com/poll/01C32ZRKE5KJ746Y6HN65VGRN5/Brazilian%20Portuguese/vote)
[](https://api.gh-polls.com/poll/01C32ZRKE5KJ746Y6HN65VGRN5/Turkish/vote)

Did I miss something? Pls let me know in the comment.

### PR DESCRIPTION
**Pull request by hql287**
This is a working demo (Form tab only) which includes translation for English, French and Vietnamese. User can set the default language in settings, hit save and the app's language would be updated immediately.

[Please have a look at a translation file format](https://github.com/hql287/Manta/blob/multiple-languages/i18n/en/form.js) and let me know what you think.

@SkyzohKey Can you review this? Thanks!

**Todos:**
- [x] Translate Invoices tab
- [x] Translate Contacts tab 
- [x] Translate Settings tab
- [x] Translate Notification
- [x] Translate Messages
- [x] Translate Dialogs
- [x] Translate `previewWindow`
- [x] Translate `tourWindow`
- [x] Fix Tests

Fix #9

### CODE REVIEW

**Comment by edmael** [comment]
@hql287 hit me up when the translation system is up to date, I'd like to add the italian language.

**Comment by hql287** [comment]
Will do! The lovely folks at [Crowin](https://crowdin.com/) just decided to give Manta a free plan as being a open source project and I’m setting it up at the moment. Will let you know when everything is ready!

**Comment by hql287** [comment]
@edmael I just updated #187 with detailed instruction on translating Manta using Crowdin. Please take a look and let me know if you have any issue. Thanks!

**Comment by edmael** [comment]
Hey @hql287 I don't see the update, but it's easy to find the project on Crowdin and work there so I already did it (part of it, will finish tomorrow).

**Comment by hql287** [comment]
@edmael Awesome! 👍 (Sorry I meant issue #9, not this PR :p )

**Comment by SkyzohKey** [comment]
Reviewed the whole PR everything looks nice to me, LGTM ! :smiley:

**Pull request merged**
