### PR TITLE
Linux Gpu Bug

### PR DESCRIPTION
**Pull request by c0b41**
ref: https://github.com/electron/electron/issues/4322
ekran goruntusu - 2018-01-05 00 11 34

### CODE REVIEW

**Comment by hql287** [comment]
Nice catch! @c0b41 👍
Any idea why those annoying scrollbars are there?

**Comment by c0b41** [comment]
@hql287 probably due to my screen dimensions

**Comment by hql287** [comment]
Do they go away if you resize the windows?

**Comment by c0b41** [comment]
@hql287 i dont no, but probably go away

**Comment by jens-t** [comment]
the hardware acceleration should definitly be on by default for linux, the performance of the the app is otherwise terrible. i understand that some users may need this as a workaround for the mentioned bug, so i would also suggest a flag to disable hardware acceleration.

**Comment by hql287** [comment]
@jens-t I don't have a Linux machine at the moment so I can't tell how this would affect the performance of the app. Would you be able to do a benchmark so we know if it's worth the effort to investigate further? Thanks!

**Comment by jens-t** [comment]
I dont know how to benchmark this. But to be more clear, when i open the app with disabled hw acceleration, the whole ui flickers arround the mouse pointer position. And Scrolling is more jumping and hanging, than smooth. So the app is unusable for me, without hwa. As i mentioned, disabling hw acceleration is a dirty workarround and not needed for a big part of the linux users.

**Pull request merged**
