### PR TITLE
Add more languages

### PR DESCRIPTION
**Pull request by hql287**
I need these languages to release the next update. Most of them is > 90% completed, so any help with approving the translation is appreciated. Thanks! 

- [x] Chinese simplified (Added in #217)
- [x] Korean (Added in #217)
- [ ] German
- [ ] Spanish
- [ ] Japanese
- [ ] Portuguese
- [ ] Portuguese, Brazilian
- [ ] Turkish

### CODE REVIEW

**Comment by Weltraumakustik** [comment]
I'll help with the German translations 🇩🇪 👍

**Comment by marcobischoff** [comment]
@hql287 do you need help for the German language?

**Comment by hql287** [comment]
@marcobischoff  👍 I just made you the proofreader for German on Crowdin. If you can take a look and approve the existing translation (and probably translate some new strings) that would be great.
Thanks!

**Comment by marcobischoff** [comment]
@hql287 the translators did a great job, only small things to change, therefor german is done.

**Comment by hql287** [comment]
@marcobischoff Awesome! Thanks!

**Comment by jens-t** [comment]
Do you need help here? Or is the only blocker left here, resolving the conflicting files and merge into dev?

Would like to add a pull Request for local dates with moment js. And a refactor of the due date and date format form fields formatted based on the current locale. Thought it makes sense to wait for this merge.

**Comment by hql287** [comment]
Closed in favour of https://github.com/hql287/Manta/pull/229

**Pull request closed without merging**
