### PR TITLE
values can be float

### LINKED ISSUE #67: Add support for decimal prices
**Is it a bug or a feature request?**
- [x] It's a bug.
**Which version are you using?**
- [x] macOS
**Which is the version/distribution of the OS?**
macOS High Sierra

Please add support for decimal prices such as 7,99€; 20,23€. Currently the ',' just gets deleted.
That'd be really nice.

### PR DESCRIPTION
**Pull request by mathieudutour**
fix #67

### CODE REVIEW

**Comment by luanmuniz** [comment]
@mathieudutour Don't forget the `step="0.01"` in the input!

**Comment by mathieudutour** [comment]
ah good catch

**Comment by cenderin** [comment]
I think a lot of people would like this into the app.  Not sure why its failing exactly, looks like its just recording some placement of the step strangely?  I implemented this locally and it works fine and everything calculates fine.  Maybe if we can get that snapchat working we can get this in the next version.  @hql287

**Comment by hql287** [comment]
This definitely is going to be included in the next version. I’m just working on other issue at the moment. Will fix this soon.

**Comment by luanmuniz** [comment]
The tests are failing because the attributes are in the wrong order

**Comment by hql287** [comment]
Thanks a lot @mathieudutour :)

**Pull request merged**
