### PR TITLE
Added pt-PT translation

### PR DESCRIPTION
**Pull request by henriquemacedo**

### CODE REVIEW

**Comment by henriquemacedo** [comment]
I just added european portuguese.
I think there are still missing fields in the translation file as _"General"_, _"Template"_, etc. right?

**Comment by hql287** [comment]
Hey @henriquemacedo, this is great. Thanks! 

And yes, my earlier PR just translated the Form tab so we’ll need Invoices, Contacts, Settings, Notifications, Dialogs... I’ll try to get the rest translated by the end of today.

But the way we add translation remains the same. do you have any issue with this so far?

**Comment by hql287** [comment]
Also, is it possible if you can ask another Portuguese speaking friend to review this translation? :)

Thanks!

**Comment by henriquemacedo** [comment]
@hql287 no problem so far!
Hey @JoaoTMDias can you review my translation of this?

**Comment by hql287** [comment]
@henriquemacedo Great! 👍 I'm trying to setup Manta on Crowin, will keep you posted.

**Comment by hql287** [comment]
@henriquemacedo & @JoaoTMDias: I just updated #187 with detailed instruction on translating Manta using Crowdin. Please take a look and let me know if you have any issue. Thanks!

**Comment by hql287** [comment]
Closing this as the translation is being taken place on Crowdin. 
Thanks @henriquemacedo 👍

**Pull request closed without merging**
