### PR TITLE
Fix preview fonts

### PR DESCRIPTION
**Pull request by jiserra**
There was a missing font file and also the font paths were wrong. I think this PR fix this.

### CODE REVIEW

**Comment by hql287** [comment]
@jiserra Hi Juan, thanks for the PR. Will test it now.

**Comment by hql287** [comment]
Doesn't look like it, because I don't think there's any difference between this 

```
url(../static/fonts/Montserrat/Montserrat-Light.ttf), format('truetype');
```

and this 

```
url('../../fonts/Montserrat/Montserrat-Light.ttf') format('truetype');
```

These will be resolved to the same path. 

How did you know that this works? 
I tried to disable Montserrat and this didn't work.

**Comment by jiserra** [comment]
I tested the build with Preview. I don't have that font on my system, so that's how I know it's working. When the fonts are not loaded, I only see sans-serif in places where Montserrat should be.

The path may work with `../../fonts` or `../static/fonts`, but definitely there were font files missing on the build and the names of the fonts assigned on the CSS were wrong. To test it, try [removing all the Montserrat fonts from your system](https://support.apple.com/guide/font-book/remove-or-disable-fonts-fntb2bcb512d), rebooting and test the build.

**Comment by hql287** [comment]
Hmm, this is really weird. I applied your changes and deactivated those fonts with [RightFont](https://rightfontapp.com/) and it still shows everything in default serif/sans-serif fonts.

**Comment by hql287** [comment]
I'm an idiot. I didn't know how I managed to [include only Italic/Medium files](https://github.com/hql287/Manta/tree/dev/static/fonts/Montserrat). Facepalm 😖

**Pull request merged**
