### PR TITLE
Add electron-react-devtools & init devtools plugins automatically

### PR DESCRIPTION
**Pull request by jens-t**
Added the electron-react-devtools package and added it with devtron to the devtools initialization.

### CODE REVIEW

**Comment by hql287** [comment]
I tried `electron-react-devtools`, it felt very hacky and didn't work out very well, especially when you have multiple profiles in your Chrome.  

At the moment, `react-devtools` and `redux-devtools` are loaded automatically if you have a `.env` file contains entries similar to this: 

```
REACT_DEV_TOOLS_PATH=/path/to/your/react-dev-tool-extension
REDUX_DEV_TOOLS_PATH=/path/to/your/redux-dev-tool-extension
```

[You can locate these paths with this instruction](https://github.com/electron/electron/blob/master/docs/tutorial/devtools-extension.md). This approach is less 'automatic' but you can load exactly the version that you want to use. For example, if there's a new version of `react-devtool`, you can just upgrade it in Chrome, then locate the path to that version and update the above value and be on your way. 

Do you think that I should document this in the README?

**Comment by hql287** [comment]
Regarding `devtron`, it's useful from time to time but to be honest I don't use it that much. Plus the fact that its development has been stopped since 2016, I think it makes more sense to load it "in-demand" by simply typing this into the console:

```js
require('devtron').install()

```

**Comment by jens-t** [comment]
> At the moment, react-devtools and redux-devtools are loaded automatically if you have a .env file ...
You can locate these paths with this instruction. This approach is less 'automatic' but you can load exactly the version that you want to use. For example, if there's a new version of react-devtool, you can just upgrade it in Chrome, then locate the path to that version and update the above value and be on your way.

Ah, thanks for the info. Didn't really understand before where the `process.env` constants are defined. so if i understand that right, you can use the via chromium installed devtools extensions also in an electron app.

that means `electron-react-devtools` are not needed, because you can use `react-devtools` & `redux.devtools`? Will try that ...

> Regarding devtron, it's useful from time to time but to be honest I don't use it that much. Plus the fact that its development has been stopped since 2016, I think it makes more sense to load it "in-demand"

the repository is still active. and the `devtools` linter section deserves a look from time to time. i thought it is not obvious enough for everyone how easy it is to install `devtron` conditionally and since its installed, i thought it's way more comfortable to init it together with the other devtools. even if you don not use it every day, there's not really a disadvantage, or?

**Comment by hql287** [comment]
> that means electron-react-devtools are not needed, because you can use react-devtools & redux.devtools? Will try that ...

Yes, that's correct! 👍 

> i thought it is not obvious enough for everyone how easy it is to install devtron conditionally and since its installed, i thought it's way more comfortable to init it together with the other devtools. 

Yeah it's more convenient but from the ux point of view, if we don't use it then there's no reason for it to be there. It's the same reason why the virtual keyboard on our phones is hidden by default. The `previewWindow` of Manta is hidden by default for the same reason. 

> even if you don not use it every day, there's not really a disadvantage, or?

Probably there's no obvious disadvantage but I would say the more extensions that the devtool need to initiate, the slower it will be. Don't have any stats to back this up but it should be true 😜

Anyway, if you strongly feel that `Devtron` should be included with other devtools, I think what we can do is add a new short-cut to initiate `Devtron` on demand.

**Comment by jens-t** [comment]
Yeah ok, i get you :laughing: 

> Anyway, if you strongly feel that Devtron should be included with other devtools, I think what we can do is add a new short-cut to initiate Devtron on demand.

Why not, and update the developer section in the readme a bit :) Would open a new pull request for that and close this one, ok?

**Comment by hql287** [comment]
> Why not, and update the developer section in the readme a bit :) Would open a new pull request for that and close this one, ok?

Sounds good to me 👍

**Comment by jens-t** [comment]
followup here: #238

**Pull request closed without merging**
