### PR TITLE
Fat Arrow Bind

### PR DESCRIPTION
**Pull request by c0b41**

### CODE REVIEW

**Comment by hql287** [comment]
@c0b41 I actually [used to write all the components this way](https://github.com/hql287/Manta/commit/d3f432f2e9f77af99bfdadf7465c11995323ec74#diff-cb0e5170d0f777e140713daf1ab4569e) but then decided to switch back to the current syntax. Can't remember why now. 

So is there any benefit of using fat arrows other than auto binding (terser code)? Or any side effect that we should be aware of?

**Comment by c0b41** [comment]
@hql287 actualy babel thing, but maybe bad idea because not ecmascript proposals in

**Comment by hql287** [comment]
@mathieudutour Any thoughts on this?

**Comment by c0b41** [comment]
@hql287 I prefer the more readable code

**Comment by mathieudutour** [comment]
I don’t think one is more readable than the other. There are pros and cons for each:

Pros:
- if you get in the habit of always using the fat arrows, you won’t forget to bind sometimes and stumble upon weird errors where `this` is not what you expect
- shorter overall

Cons:
- if you get in the habit of using the fat arrows, you will also use it for component lifecycle methods which is bad (because already bound)
- only stage 3 syntax
- less explicit

All in all, I think we should just pick one and enforce it with eslint, don’t care which one

**Comment by hql287** [comment]
@c0b41 I wouldn't which one is more readable than the other (the fat arrow is definitely shorter, though 👍). I think I came back to the current syntax because it's more explicit and I wanted to void any potential side effects. Plus, I guess it's safer to stick to what the folks at FB are using. 

@mathieudutour Shouldn't this be in **cons** instead of **pros**? (and probably **will** instead of **won't**?) 😄
> if you get in the habit of always using the fat arrows, you won’t forget to bind sometimes and stumble upon weird errors where this is not what you expect

**Comment by mathieudutour** [comment]
well no, it's a pro for using fat arrows: if you **don't use** it and you forget to bind, you will have errors that are weird to track down because you use `this` and that's not what you expect

**Comment by hql287** [comment]
Ah, gotcha! 👍

I thought what you meant was

> if you get in the habit of always using the fat arrows, you **will** forget to bind sometimes (because the fat arrows do it for you) and you'll stumble upon weird errors where this is not what you expect

**Comment by c0b41** [comment]
@hql287 Dan Abramov answer https://www.reddit.com/r/reactjs/comments/54xnao/fat_arrow_vs_autobind_vs_bindbindbindbindbind/d85wj0l/ alson

**Comment by c0b41** [comment]
Also manta not only binding event see: https://github.com/hql287/Manta/blob/dev/app/components/form/Currency.jsx#L19

**Comment by mathieudutour** [comment]
well then it's a bug and it should be fixed, it's not a justification for fat arrows. I'd say it's even the opposite: if you start to use fat arrows, you won't even think about what you are binding and it will make performances worse

**Comment by hql287** [comment]
> Also manta not only binding event see: https://github.com/hql287/Manta/blob/dev/app/components/form/Currency.jsx#L19

This is actually my bad because I thought the only place that I won't need to bind is lifecycle methods. Looks like I do this on other components, too. 

Anyway, thanks for pointing this out! Do you have any other good read on this topic that I should check out? 👍

**Comment by hql287** [comment]
@c0b41 Back to the main topic, if I understand Dan correctly, I think he recommends binding manually because you'll only need to bind the event handlers and if you have too many of them you should split the component into smaller ones. So either way, it will hardly become a big problem, it's more like a personal preference to me.

**Pull request closed without merging**
